config/routes.rb
Theclaw::Application.routes.draw do
  resources :tracks

  
  get "pull_data" => "tracks#pull_data"

  root :to => 'tracks#index'

end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :asset, :engine_coolant_temp, :recorded_at, :total_used_fuel, :vehicle_speed, :data_point_id
  validates :data_point_id, :uniqueness => true, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fetch_data_controller.rb
class FetchDataController < ApplicationController

require 'json'
require 'base64'
require 'net/http'



  def pull_data
    url = URI.parse('http://www.example.com/index.html')
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port) {|http|
    http.request(req)
    }
    puts res.body
  end



# Let's imagine your web server received a POST request with this body:
request_body =<<EOF
[
  {
    "meta": {
      "account": "AccountExample",
      "event": "track"
    },
    "payload": {
      "id": 342656641079967767,
      "id_str": "342656641079967767",
      "asset": "359551XXXXX6317",
      "recorded_at": "2012-08-03T14:25:25Z",
      "received_at": "2012-08-03T14:26:28Z",
      "loc": [
        2.36687,
        48.78354
      ],
      "fields": {
        "GPS_SPEED": {
          "b64_value": "AAAAKg=="
        }
      }
    }
  }
]
EOF

events = JSON.parse(request_body)

events.each do |event|
  next if event['meta']['event'] != 'track'

  event['payload']['fields'].each do |field, data|
    if field == 'GPS_SPEED'
      b64_value = data['b64_value']
      decoded_value = Base64.decode64(b64_value).unpack('B*').first.to_i(2)
      puts "Decoded value: #{decoded_value}"
      km_h = decoded_value.to_f / 1000 * 1.852
      puts "Speed: #{km_h} / h"
    end
  end
end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
require 'json'
require 'base64'
require 'net/http'
require 'uri'

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tracks }
    end
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
    @track = Track.find(params[:id])
    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @track }
    end
  end

  def pull_data
    url = URI.parse('http://neweagleinte.integration.cloudconnect.io/api/v3/tracks')
    @req = Net::HTTP::Get.new(url.to_s)
    @req.basic_auth("9aeb6d38b108918a19c2de9ac6ce10a30c27dee3", "X")
    res = Net::HTTP.start(url.host, url.port) {|http|
    http.request(@req)
    }
    @request_body = res.body
    @result = JSON.parse(@request_body)
    
    @result.each do |event|
     @track = Track.new
      @track.data_point_id = event["id"]
      @track.asset = event["asset"]
      @track.latitude = event["location"][0]
      @track.longitude = event["location"][1]
      @track.recorded_at = event["recorded_at"]
      event["fields"].each do |field, data|
          if field == 'FMS_TOTAL_USED_FUEL'
            b64_value = data['b64_value']
            @decoded_value_fuel = Base64.decode64(b64_value).unpack('L>').first.to_i
            @track.total_used_fuel = @decoded_value_fuel
           
          end
          if field == 'FMS_ENGINE_COOLANT_TEMP'
            b64_value = data['b64_value']
            @decoded_value_temp = Base64.decode64(b64_value).unpack('L>').first.to_i
            @track.engine_coolant_temp = @decoded_value_temp
           
          end
      end
     
        @track.save
    end

    respond_to do |format|
      format.html 
      format.json { render json: @decoded_value}
    end
    
  end


  # Decodes base 64 value into ascii integers
  # 
  def decode(request_body)
  events = JSON.parse(request_body)

    events.each do |event|
      next if event['meta']['event'] != 'track'

        event['payload']['fields'].each do |field, data|
          if field == 'GPS_SPEED'
            b64_value = data['b64_value']
            decoded_value = Base64.decode64(b64_value).unpack('B*').first.to_i(2)
            puts "Decoded value: #{decoded_value}"
            km_h = decoded_value.to_f / 1000 * 1.852
            puts "Speed: #{km_h} / h"
          end
      end
    end
  end


  # GET /tracks/new
  # GET /tracks/new.json
  def new
    @tracks = Track.new
   
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @track }
    end
  end

  # GET /tracks/1/edit
  def edit
    @track = Track.find(params[:id])
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(params[:track])

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render json: @track, status: :created, location: @track }
      else
        format.html { render action: "new" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tracks/1
  # PUT /tracks/1.json
  def update
    @track = Track.find(params[:id])

    respond_to do |format|
      if @track.update_attributes(params[:track])
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track = Track.find(params[:id])
    @track.destroy

    respond_to do |format|
      format.html { redirect_to tracks_url }
      format.json { head :no_content }
    end
  end






end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fetch_data_helper.rb
module FetchDataHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/home/index.html.erb
<h1>Tracks</h1>
<p>Click to show the latest tracks:

<%=link_to 'tracks', tracks_path%>

</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Theclaw</title>
  <link rel="stylesheet" href="http://twitter.github.io/bootstrap/1.3.0/bootstrap.min.css" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="topbar">
    <div class="fill">
      <div class="container">
        <a class="brand" href="/">The Clawer</a>
        <ul class="nav">
          <li class="active"><a href="/tracks">tracks</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <%= yield %>
  </div>
  
  <footer>
    <div class="container">
      New Eagle 2013
    </div>
  </footer>
</body>
</html>

app/views/tracks/_form.html.erb
<%= form_for(@track) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recorded_at %><br />
    <%= f.datetime_select :recorded_at %>
  </div>
  <div class="field">
    <%= f.label :asset %><br />
    <%= f.text_field :asset %>
  </div>
  <div class="field">
    <%= f.label :vehicle_speed %><br />
    <%= f.number_field :vehicle_speed %>
  </div>
  <div class="field">
    <%= f.label :engine_coolant_temp %><br />
    <%= f.number_field :engine_coolant_temp %>
  </div>
  <div class="field">
    <%= f.label :total_used_fuel %><br />
    <%= f.number_field :total_used_fuel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<!-- Ready for release -->
<div id="container" style="width:100%; height:400px;"></div>

<h1>Telematics Data Points</h1>
<table class="table-hover">
  <tr>
    <th>ID</th>
    <th>Data Point ID</th>
    <th>Recorded at</th>
    <th>Asset</th>
    <th>Vehicle speed</th>
    <th>Engine coolant temp</th>
    <th>Total used fuel</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tracks.each do |track| %>
  <tr>

    <td><%= track.id %></td>
    <td><%= track.data_point_id %></td>
    <td><%= track.recorded_at %></td>
    <td><%= track.asset %></td>
    <td><%= track.vehicle_speed %></td>
    <td><%= track.engine_coolant_temp %></td>
    <td><%= track.total_used_fuel %></td>
    <td><%= link_to 'Show', track %></td>
    <td><%= link_to 'Edit', edit_track_path(track) %></td>
    <td><%= link_to 'Destroy', track, method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Refresh Data', pull_data_path, class: "btn btn-primary" %>

<script>
$(function () { 
    $('#container').highcharts({
        chart: {
            type: 'line',
            zoomType: 'x'
        },
        title: {
            text: 'Fuel Consumption'
        },
        xAxis: {
            categories: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
        },
        yAxis: {
            title: {
                text: 'Average Fuel Consumption [MPG]'
            }
        },
        series: [{
            name: 'Chevrolet Corsa',
            data: [28, 29, 27, 22, 28, 26, 30, 29, 27, , , ,]
        }, {
            name: 'Fiat Uno',
            data: [35, 36, 34, 30, 37, 38, 37, 37, 38, , , ,]
        }]
    });
});
</script>

app/views/tracks/pull_data.html.erb
<h1>Fresh data from the cloud has been fetched!  Hit the back button below </h1> 
<center>
<%= link_to 'Back', tracks_path, class: "btn btn-primary" %>  
</center>
<%#= render 'form' %>



<!-- <p><%=@result %></p> -->

<%#= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Recorded at:</b>
  <%= @track.recorded_at %>
</p>

<p>
  <b>Asset:</b>
  <%= @track.asset %>
</p>

<p>
  <b>Vehicle speed:</b>
  <%= @track.vehicle_speed %>
</p>

<p>
  <b>Engine coolant temp:</b>
  <%= @track.engine_coolant_temp %>
</p>

<p>
  <b>Total used fuel:</b>
  <%= @track.total_used_fuel %>
</p>


<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>